#!/bin/bash
#!/usr/bin/bash

echo "Teste 3: Entrada: 947 / Espera-se: Invalido"
echo 947 | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 4: Entrada: edu@r / Espera-se: Invalido"
echo "edu@r" | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 5: Entrada: Espaço em Branco / Espera-se: Invalido"
echo " " | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 6: Entrada: eduardodebrum / Espera-se: Invalido"
echo "eduardodebrum" | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 7: Entrada: e3d / Espera-se: Válido"
echo "e3d" | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
