#!/bin/bash
#!/usr/bin/bash

echo "Teste 3: Entrada: 947 / Saída Esperada: Invalido"
echo 947 | ./identifier.exe
echo "Teste 4: Entrada: edu@r / Saída Esperada: Invalido"
echo "edu@r" | ./identifier.exe
echo "Teste 5: Entrada: Espaço em Branco / Saída Esperada: Invalido"
echo " " | ./identifier.exe
echo "Teste 6: Entrada: eduardodebrum / Saída Esperada: Invalido"
echo "eduardodebrum" | ./identifier.exe
echo "Teste 7: Entrada: e3d / Saída Esperada: Válido"
echo "e3d" | ./identifier.exe
