#!/bin/bash
#!/usr/bin/bash

echo "Teste 3: Entrada: 947 / Saída Esperada: Invalido"
echo 947 | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 4: Entrada: edu@r / Saída Esperada: Invalido"
echo "edu@r" | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 5: Entrada: Espaço em Branco / Saída Esperada: Invalido"
echo " " | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 6: Entrada: eduardodebrum / Saída Esperada: Invalido"
echo "eduardodebrum" | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
echo "Teste 7: Entrada: e3d / Saída Esperada: Válido"
echo "e3d" | valgrind --leak-check=full --show-leak-kinds=all ./identifier.exe
